branch-defaults:
  main:
    environment: null
    group_suffix: null
deploy:
  artifact: target/frtechassignment-0.0.1-SNAPSHOT.jar
global:
  application_name: frtechassignment
  branch: null
  default_ec2_keyname: null
  default_platform: Corretto 11 running on 64bit Amazon Linux 2
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
