server:
  port: 5000

spring:
  mvc:
    format:
      date: dd-MM-yyyy

transactiondata:
  storage:
    file:
      path: src/main/resources/transactions.json
  externalsystem:
    log:
      path: src/main/resources/externalsystem.event.log
